### ISSUE TITLE
booksonic not starting up in docker.

### ISSUE THREAD

**Issue by kkasberg** [linuxserver/docker-booksonic#15]
I am not getting booksonic to start.   I am running the latest docker container.
`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    1000,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
2019-12-22 01:33:52.311:INFO::main: Logging initialized @278ms,
2019-12-22 01:33:52.324:INFO:oejr.Runner:main: Runner,
2019-12-22 01:33:52.605:INFO:oejs.Server:main: jetty-9.3.14.v20161028,
2019-12-22 01:33:54.191:INFO:oejs.AbstractConnector:main: Started ServerConnector@679b62af{HTTP/1.1,[http/1.1]}{0.0.0.0:4040},
Exception in thread "main" java.lang.NoSuchMethodError: org.springframework.core.CollectionFactory.createConcurrentMapIfPossible(I)Ljava/util/Map;,
	at org.springframework.web.context.ContextLoader.<clinit>(ContextLoader.java:153),
	at org.springframework.web.context.ContextLoaderListener.createContextLoader(ContextLoaderListener.java:53),
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:44),
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843),
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533),
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816),
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345),
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404),
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366),
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778),
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262),
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61),
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.server.Server.start(Server.java:422),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61),
	at org.eclipse.jetty.server.Server.doStart(Server.java:389),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.runner.Runner.run(Runner.java:495),
	at org.eclipse.jetty.runner.Runner.main(Runner.java:536),`

**Comment by watson387** [comment]
I'm getting the exact same log as above.  Server is up but getting

```
HTTP ERROR: 404
Problem accessing /. Reason:

    Not Found
```
when trying to access.

**Comment by thelamer** [comment]
https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/booksonic/latest/index.html

We get this also give me a moment to find out what version this occured in.

**Comment by thelamer** [comment]
Looks like an issue with their latest release please use :
```
linuxserver/booksonic:1.1.Release-ls46
```
Until we find a solution. 

https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/booksonic/1.1.Release-ls46/index.html

**Comment by CHBMB** [comment]
Closed by @thelamer in this PR

https://github.com/linuxserver/docker-booksonic/pull/16
