### ISSUE TITLE
Sonos connect java error

### ISSUE THREAD

**Issue by jt196** [linuxserver/docker-booksonic#24]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Attempting to turn on Sonos service in settings -> sonos.
I know Booksonic isn't Subsonic, but I was hoping to get a little further than this... 

## Current Behavior
check "Enable Sonos service" and save pulls up an error message. Looks like it's related to Java.

```
Exception | javax.servlet.ServletException
-- | --
Message | org.springframework.web.util.NestedServletException:  Request processing failed; nested exception is  java.lang.NullPointerException
Java version | Private Build 1.8.0_252
Operating system | Linux 4.4.59+
Server | jetty/9.4.24.v20191120
Memory | Used 196 of 418 MB
Stack trace | javax.servlet.ServletException: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162) 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) 	at org.eclipse.jetty.server.Server.handle(Server.java:500) 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547) 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270) 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388) 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) 	at java.lang.Thread.run(Thread.java:748) Caused by: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:583) 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:511) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) 	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1400) 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760) 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:265) 	at org.acegisecurity.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:107) 	at org.acegisecurity.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:72) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.ui.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:166) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.wrapper.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:81) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.ui.basicauth.BasicProcessingFilter.doFilter(BasicProcessingFilter.java:173) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.ui.logout.LogoutFilter.doFilter(LogoutFilter.java:110) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249) 	at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275) 	at org.acegisecurity.util.FilterChainProxy.doFilter(FilterChainProxy.java:149) 	at org.acegisecurity.util.FilterToBeanProxy.doFilter(FilterToBeanProxy.java:98) 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) 	at net.sourceforge.subsonic.filter.RequestEncodingFilter.doFilter(RequestEncodingFilter.java:43) 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) 	at net.sourceforge.subsonic.filter.ParameterDecodingFilter.doFilter(ParameterDecodingFilter.java:54) 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604) 	at net.sourceforge.subsonic.filter.BootstrapVerificationFilter.doFilter(BootstrapVerificationFilter.java:59) 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596) 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545) 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590) 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607) 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297) 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485) 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577) 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212) 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221) 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) 	... 17 more Caused by: java.lang.NullPointerException 	at net.sourceforge.subsonic.service.UPnPService.getSonosControllerHosts(UPnPService.java:174) 	at net.sourceforge.subsonic.service.SonosService.setMusicServiceEnabled(SonosService.java:189) 	at net.sourceforge.subsonic.controller.SonosSettingsController.handleParameters(SonosSettingsController.java:85) 	at net.sourceforge.subsonic.controller.SonosSettingsController.handleRequestInternal(SonosSettingsController.java:51) 	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153) 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48) 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875) 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807) 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571) 	... 68 more

```

## Environment
Synology DS918+, Intel processor, Docker. 
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)
```
docker create \
  --name=booksonic \
  -e PUID=1029 \
  -e PGID=100 \
  -e TZ=Europe/London \
  -e CONTEXT_PATH=url-base \
  -p 4040:4040 \
  -v /volume1/docker/booksonic/config:/config \
  -v /volume1/docker/booksonic/othermedia:/othermedia \
  -v /volume1/docker/booksonic/podcasts:/podcasts \
  -v /volume1/audiobooks:/audiobooks \
  --restart unless-stopped \
  linuxserver/booksonic
```

## Docker logs

	```
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: 
java.lang.NullPointerException
	at net.sourceforge.subsonic.service.UPnPService.getSonosControllerHosts(UPnPService.java:174)
	at net.sourceforge.subsonic.service.SonosService.setMusicServiceEnabled(SonosService.java:189)
	at net.sourceforge.subsonic.controller.SonosSettingsController.handleParameters(SonosSettingsController.java:85)
	at net.sourceforge.subsonic.controller.SonosSettingsController.handleRequestInternal(SonosSettingsController.java:51)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:511)

```

**Comment by j0nnymoe** [comment]
This would be a booksonic issue, not a container issue though as booksonic is no longer developed, I suspect this won't get fixed.
